### ISSUE TITLE
Type id handling not implemented for java.util.Collections$UnmodifiableMap["metadata.token.claims"]

### ISSUE THREAD

**Issue by sskjames** [spring-projects/spring-authorization-server#1049]
**Describe the bug**
I'm getting this error when I try to obtain an access token using the client credentials saved in db.
Here's my environment:  Spring Authorization Server 0.4.0, Spring Security 5.8, Spring 5.3, Java 11 and MySQL.

Here's my AuthorizationServerConfig (almost the same as in the samples):

    @Bean
    public RegisteredClientRepository registeredClientRepository(JdbcTemplate jdbcTemplate)
    {
        JdbcRegisteredClientRepository repository = new JdbcRegisteredClientRepository(jdbcTemplate);
        if (repository.findByClientId("client") == null) {
            repository.save(newRegisteredClient());
        }
        return repository;
    }

    @Bean
    public OAuth2AuthorizationService authorizationService(JdbcTemplate jdbcTemplate,
                                                           RegisteredClientRepository registeredClientRepository)
    {
        return new JdbcOAuth2AuthorizationService(jdbcTemplate, registeredClientRepository);
    }

    RegisteredClient newRegisteredClient()
    {
        return RegisteredClient.withId(UUID.randomUUID().toString())
                .clientId(restApiClient.getClientId())
                .clientSecret("{noop}" + restApiClient.getSecret())
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
                .build();
    }

```
java.lang.IllegalArgumentException: Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: java.util.Collections$UnmodifiableMap["metadata.token.claims"]->java.util.Collections$UnmodifiableMap["nbf"])
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService$OAuth2AuthorizationParametersMapper.writeMap(JdbcOAuth2AuthorizationService.java:584)
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService$OAuth2AuthorizationParametersMapper.toSqlParameterList(JdbcOAuth2AuthorizationService.java:570)
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService$OAuth2AuthorizationParametersMapper.apply(JdbcOAuth2AuthorizationService.java:519)
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService$OAuth2AuthorizationParametersMapper.apply(JdbcOAuth2AuthorizationService.java:477)
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService.insertAuthorization(JdbcOAuth2AuthorizationService.java:207)
	at org.springframework.security.oauth2.server.authorization.JdbcOAuth2AuthorizationService.save(JdbcOAuth2AuthorizationService.java:189)
	at org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientCredentialsAuthenticationProvider.authenticate(OAuth2ClientCredentialsAuthenticationProvider.java:155)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
	at org.springframework.security.oauth2.server.authorization.web.OAuth2TokenEndpointFilter.doFilterInternal(OAuth2TokenEndpointFilter.java:167)
```

**To Reproduce**
 - Use JdbcRegisteredClientRepository and JdbcOAuth2AuthorizationService with MySql as the db.
 - Register a client
 - Obtain access token using the saved client credentials

**Expected behavior**
Credentials must be validated and Access Token should be returned.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
