### ISSUE TITLE
ClientSecretPostAuthenticationConverter Error : Client credentials MUST NOT be included in the request URI.

### ISSUE THREAD

**Issue by iqolome** [spring-projects/spring-authorization-server#1425]
**Describe the bug**

**org.springframework.security**:**spring-security-oauth2-authorization-server**:**1.1.3**
**org.springframework.security.oauth2.server.authorization.web.authentication.ClientSecretPostAuthenticationConverter**

*Client credentials MUST NOT be included in the request URI.*

**To Reproduce**
Steps to reproduce the behavior.

```sh
# Post 
http://localhost:8888/oauth2/token?client_id=xxxxx&client_secret=xxxxx&grant_type=authorization_code&code=xxxxx&redirect_uri=http:%2F%2Flocalhost:8888%2Foauth-view
```

```log

org.springframework.security.oauth2.core.OAuth2AuthenticationException: Client credentials MUST NOT be included in the request URI.
	at org.springframework.security.oauth2.server.authorization.web.authentication.ClientSecretPostAuthenticationConverter.convert(ClientSecretPostAuthenticationConverter.java:81) ~[spring-security-oauth2-authorization-server-1.1.3.jar:1.1.3]
	at org.springframework.security.oauth2.server.authorization.web.authentication.DelegatingAuthenticationConverter.convert(DelegatingAuthenticationConverter.java:59) ~[spring-security-oauth2-authorization-server-1.1.3.jar:1.1.3]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2ClientAuthenticationFilter.doFilterInternal(OAuth2ClientAuthenticationFilter.java:115) ~[spring-security-oauth2-authorization-server-1.1.3.jar:1.1.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.13.jar:6.0.13]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.5.jar:6.1.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.5.jar:6.1.5]
	at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.5.jar:6.1.5]

```

>  I think there is a problem with this code, the above code requires "client_id", "client_secret", but the following judgment code requires that the argument must not contain these two parameters,

```java



package org.springframework.security.oauth2.server.authorization.web.authentication;

public final class ClientSecretPostAuthenticationConverter implements AuthenticationConverter {

	@Nullable
	@Override
	public Authentication convert(HttpServletRequest request) {
		MultiValueMap<String, String> parameters = OAuth2EndpointUtils.getParameters(request);

		// client_id (REQUIRED)
		String clientId = parameters.getFirst(OAuth2ParameterNames.CLIENT_ID);
		if (!StringUtils.hasText(clientId)) {
			return null;
		}

		if (parameters.get(OAuth2ParameterNames.CLIENT_ID).size() != 1) {
			throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_REQUEST);
		}

		// client_secret (REQUIRED)
		String clientSecret = parameters.getFirst(OAuth2ParameterNames.CLIENT_SECRET);
		if (!StringUtils.hasText(clientSecret)) {
			return null;
		}

		if (parameters.get(OAuth2ParameterNames.CLIENT_SECRET).size() != 1) {
			throw new OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_REQUEST);
		}


              //  I think there is a problem with this code, the above code requires "client_id", "client_secret", but the following judgment code requires that the argument must not contain these two parameters

		String queryString = request.getQueryString();
		if (StringUtils.hasText(queryString) &&
				(queryString.contains(OAuth2ParameterNames.CLIENT_ID) ||
						queryString.contains(OAuth2ParameterNames.CLIENT_SECRET))) {
			OAuth2Error error = new OAuth2Error(
					OAuth2ErrorCodes.INVALID_REQUEST,
					"Client credentials MUST NOT be included in the request URI.",
					null);
			throw new OAuth2AuthenticationException(error);
		}

		Map<String, Object> additionalParameters = OAuth2EndpointUtils.getParametersIfMatchesAuthorizationCodeGrantRequest(request,
				OAuth2ParameterNames.CLIENT_ID,
				OAuth2ParameterNames.CLIENT_SECRET);

		return new OAuth2ClientAuthenticationToken(clientId, ClientAuthenticationMethod.CLIENT_SECRET_POST, clientSecret,
				additionalParameters);
	}

}


```

**Expected behavior**

Successfully obtain the token

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jgrandja** [comment]
@iqolome Client credentials are not allowed as query parameters in a POST, instead, they MUST be in the request body. This was recently reported as a bug and fixed in gh-1378. Closing this as a duplicate.

**Comment by jack5505** [comment]
I also wanted to comment it it's better to send in POST request body instead of sending it in url in open way.
