### ISSUE TITLE
StackOverflowError Occur when customizing AuthenticationProvider

### ISSUE THREAD

**Issue by hundanLi** [spring-projects/spring-authorization-server#1554]
**Describe the bug**
I meet a StackOverflowError when implements my own AuthenticationProvider

**To Reproduce**
 Throw an OAuth2AuthenticationException(OAuth2ErrorCodes.INVALID_CLIENT);  in authenticate() method
 jdk version: 17
spring-oauth2-authorization-server version: 1.2.2
springboot version: 3.2.3

**Expected behavior**
Authentication Error repsonse

**Sample**
java.lang.StackOverflowError: null
	at org.springframework.aop.support.AopUtils.isEqualsMethod(AopUtils.java:159) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:172) ~[spring-aop-6.1.4.jar:6.1.4]
	at jdk.proxy2/jdk.proxy2.$Proxy71.authenticate(Unknown Source) ~[na:na]

**Comment by sjohnr** [comment]
@hundanLi we generally ask that you provide a sample or test that reproduces your issue for issues with customizations like you are describing. Please provide a minimal sample or a test that reproduces the issue so we can look into this issue further.
