### ISSUE TITLE
upgrade from 0.2.0 to 0.2.1: java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"

### ISSUE THREAD

**Issue by benothman** [spring-projects/spring-authorization-server#528]
I tried to upgrade to the latest release 0.2.1 from 0.2.0 but an exception was thrown during the login process. I am not sure where this could come from but it seems to look for a PasswordEncoder by passing an `null` value of the `id`.

I tried to debug it and I noticed that it tries to match password multiple time with the correct `bcrypt` password encoder and then it fails because of `null` id

*Note:* nothing has changed in my code a part from the version of the authorization-server.

```
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:254) ~[spring-security-crypto-5.5.3.jar:5.5.3]
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:202) ~[spring-security-crypto-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientAuthenticationProvider.authenticate(OAuth2ClientAuthenticationProvider.java:112) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2ClientAuthenticationFilter.doFilterInternal(OAuth2ClientAuthenticationFilter.java:110) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2AuthorizationServerMetadataEndpointFilter.doFilterInternal(OAuth2AuthorizationServerMetadataEndpointFilter.java:76) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.web.NimbusJwkSetEndpointFilter.doFilterInternal(NimbusJwkSetEndpointFilter.java:85) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.oidc.web.OidcProviderConfigurationEndpointFilter.doFilterInternal(OidcProviderConfigurationEndpointFilter.java:75) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.oauth2.server.authorization.web.OAuth2AuthorizationEndpointFilter.doFilterInternal(OAuth2AuthorizationEndpointFilter.java:140) ~[spring-security-oauth2-authorization-server-0.2.1.jar:0.2.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.13.jar:5.3.13]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.5.3.jar:5.5.3]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.5.3.jar:5.5.3]

```

**Comment by jgrandja** [comment]
@benothman This issue is related to the changes applied in gh-496. To resolve this, ensure the `RegisteredClient.clientSecret` is configured with the correct hashing algorithm. If it's stored as plain text then it should be `{noop}the_secret`. See this specific [change](https://github.com/spring-projects/spring-authorization-server/commit/f0b19f30d1cf0ddaf12a0414c7a845c1b55eeb0e#diff-f5dda852b1171514d05869e1b0f112635a7459e927b66454acba303bdeecd0b8R69) in the associated commit.

I'll close this as the suggested solution should work. We can reopen if you're still having issues.

**Comment by benothman** [comment]
Perfect, thanks.

**Comment by oridool** [comment]
Hi @jgrandja , I also have the same error after upgrade.
Can you clarify what does it mean `"ensure the RegisteredClient.clientSecret is configured with the correct hashing algorithm."` ?
Is there a new property on the client I should set before calling `save()` ?
Or is it expected that now my code will encrypt the secret using my own encoder?

It would be nice if you can provide an example, since right now the example is using `{noop}'.

**Comment by benothman** [comment]
@oridool 
you can just use a PasswordEncoder and encode the client secret when setting that value
`.clientSecret(passwordEncoder.encode("the_secret"))`

**Comment by oridool** [comment]
thanks @benothman , this is exactly what I did :) 
I thought there is another better way that I was missing...

**Comment by sjohnr** [comment]
@oridool that's currently the correct way to do it. The reason is that it's challenging to handle saving a new client vs. saving an existing client, as the secret would get double-encoded if the framework encodes it for you. It could be solved in the future with a separate method for updating a client secret. We're striving for backwards compatibility at the moment, so we'll be deferring that API change for a future release.

**Comment by hezhongfeng** [comment]
@sjohnr 
client-secret: secret
and server must save {noop}secret
want a bad match method.
It took me a lot of time to figure it out

**Comment by hezhongfeng** [comment]
I think use `new BCryptPasswordEncoder()` to match,but is not.

**Comment by sjohnr** [comment]
Sorry @hezhongfeng, apologies but I don't quite follow.
