### ISSUE TITLE
ConcurrentModificationException on load tests

### ISSUE THREAD

**Issue by dsukhoroslov** [spring-projects/spring-authorization-server#766]
**Describe the bug**
We develop a custom Auth Server, it is based on the spring-authorization-server project, v.0.3.0. In load tests after running 20+ concurrent login sessions I see the following stack trace time to time:

```
2022-06-06 13:20:47.905 DEBUG 1 --- [http-nio-9000-exec-2201] o.s.security.web.FilterChainProxy        : Securing POST /oauth2/token
2022-06-06 13:20:47.906 DEBUG 1 --- [http-nio-9000-exec-2201] w.c.HttpSessionSecurityContextRepository : Retrieved SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=13158530-f056-4cab-9c68-b7aacfb540d1, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.0.6.71, SessionId=261715E49D3BB35622225C6FFE58EED0], Granted Authorities=[SCOPE_openid, SCOPE_profile, SCOPE_email]]]
2022-06-06 13:20:47.906 DEBUG 1 --- [http-nio-9000-exec-2201] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=13158530-f056-4cab-9c68-b7aacfb540d1, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=10.0.6.71, SessionId=261715E49D3BB35622225C6FFE58EED0], Granted Authorities=[SCOPE_openid, SCOPE_profile, SCOPE_email]]]
...
2022-06-06 13:20:47.953 DEBUG 1 --- [http-nio-9000-exec-2201] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
2022-06-06 13:20:47.954 ERROR 1 --- [http-nio-9000-exec-2201] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source)
	at org.springframework.security.oauth2.server.authorization.InMemoryOAuth2AuthorizationService.findByToken(InMemoryOAuth2AuthorizationService.java:138)
	at org.springframework.security.oauth2.server.authorization.authentication.CodeVerifierAuthenticator.authenticate(CodeVerifierAuthenticator.java:77)
	at org.springframework.security.oauth2.server.authorization.authentication.CodeVerifierAuthenticator.authenticateIfAvailable(CodeVerifierAuthenticator.java:66)
	at org.springframework.security.oauth2.server.authorization.authentication.ClientSecretAuthenticationProvider.authenticate(ClientSecretAuthenticationProvider.java:111)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
```

The exception occurs in the InMemoryOAuth2AuthorizationService class, so it should be reproduceable on a clean spring-authorization-server instance, probably. 

Thanks, Denis

**Comment by sjohnr** [comment]
@dsukhoroslov, thanks for the report! Please note:

https://github.com/spring-projects/spring-authorization-server/blob/d46bdfc80b2856fe030135d3ea872ba1ba7c635a/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/InMemoryOAuth2AuthorizationService.java#L37

As this implementation of `OAuth2AuthorizationService` is for getting started and not for production use, I don't believe we would need to pursue a fix. You are recommended to switch to `JdbcOAuth2AuthorizationService`. You can configure one by registering an `@Bean` (see [docs](https://docs.spring.io/spring-authorization-server/docs/current/reference/html/core-model-components.html#oauth2-authorization-service)), as demonstrated in [the default sample](https://github.com/spring-projects/spring-authorization-server/blob/d46bdfc80b2856fe030135d3ea872ba1ba7c635a/samples/default-authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L97-L100). With that in mind, I'm going to close this for now. If there's something you think I've missed, please feel free to add additional comments and we can re-open if necessary.

**Comment by dsukhoroslov** [comment]
Thanks @sjohnr, I see now. But `JdbcOAuth2AuthorizationServer` is not an option in my case, as I need a lightweight in-memory solution (my Auth Server is just a bridge between existing IAM platform and external service which does the real authentication using protocols other than OAuth2/OIDC) and has no persistence layer. What if I'll try to fix the issue myself and provide a PR? As of now it looks like access to `initializedAuthorizations` map just requires a bit more synchronization..

**Comment by dsukhoroslov** [comment]
Yes, so far I increased `MaxSizeHashMap` size to 256 and added a small fix to findByToken method:

```
    public OAuth2Authorization findByToken(String token, @Nullable OAuth2TokenType tokenType) {
        Assert.hasText(token, "token cannot be empty");
        for (OAuth2Authorization authorization : this.authorizations.values()) {
            if (hasToken(authorization, token, tokenType)) {
                return authorization;
            }
        }
        List<OAuth2Authorization> values = new ArrayList<>(this.initializedAuthorizations.values());
        for (OAuth2Authorization authorization : values) {
            if (hasToken(authorization, token, tokenType)) {
                return authorization;
            }
        }
        return null;
    }
```
this solves the issue with `ConcurrentModificationException` for now, so testing it further..
